/**
 * Centralized SEO helpers — JSON-LD structured data generators.
 * All schema is JSON-LD per project convention. URLs resolve against BASE_URL.
 */
import type { BlogPost } from "@/data/blog-posts";
import type { ServiceDetail } from "@/data/services";
import { contact } from "@/data/contact";

export const BASE_URL = "https://indiavisaexperts.com";
export const ORG_NAME = "India Visa Experts";
// Branded image generated by app/opengraph-image.tsx (no static asset required).
const LOGO_URL = `${BASE_URL}/opengraph-image`;

const abs = (path: string) => (path.startsWith("http") ? path : `${BASE_URL}${path}`);

/** Sitewide organization identity. */
export function organizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    "@id": `${BASE_URL}/#organization`,
    name: ORG_NAME,
    description:
      "Independent visa and immigration consulting service for India. Not affiliated with the Government of India.",
    url: BASE_URL,
    logo: LOGO_URL,
    image: LOGO_URL,
    telephone: contact.phoneTel,
    email: contact.email,
    priceRange: "$$",
    address: {
      "@type": "PostalAddress",
      streetAddress: contact.address.street,
      addressLocality: contact.address.locality,
      addressRegion: contact.address.region,
      addressCountry: contact.address.country,
    },
    areaServed: { "@type": "Country", name: "India" },
    sameAs: [
      contact.social.linkedin,
      contact.social.facebook,
      contact.social.twitter,
    ],
    serviceType: [
      "Business Visa Consulting",
      "Employment Visa Consulting",
      "FRRO Registration",
      "Immigration Advisory",
    ],
  };
}

/** Site-level entity for sitelinks/search understanding. */
export function websiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${BASE_URL}/#website`,
    name: ORG_NAME,
    url: BASE_URL,
    publisher: { "@id": `${BASE_URL}/#organization` },
    inLanguage: "en-US",
  };
}

/** Breadcrumb trail. Pass items in order from Home → current page. */
export function breadcrumbSchema(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: abs(item.path),
    })),
  };
}

/** FAQ rich-result schema. Must mirror the FAQs visibly rendered on the page. */
export function faqSchema(faqs: { question: string; answer: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.question,
      acceptedAnswer: { "@type": "Answer", text: f.answer },
    })),
  };
}

/** Service offering schema for service pages. */
export function serviceSchema(service: ServiceDetail) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name: service.title,
    serviceType: service.shortTitle,
    description: service.metaDescription || service.description,
    url: `${BASE_URL}/${service.slug}`,
    provider: { "@id": `${BASE_URL}/#organization` },
    areaServed: { "@type": "Country", name: "India" },
    audience: { "@type": "Audience", audienceType: "Foreign nationals and companies in India" },
  };
}

/** Article/blog schema. */
export function articleSchema(post: BlogPost) {
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.metaDescription || post.excerpt,
    datePublished: post.publishedAt,
    dateModified: post.publishedAt,
    author: { "@type": "Organization", name: post.author || ORG_NAME, url: BASE_URL },
    publisher: {
      "@type": "Organization",
      name: ORG_NAME,
      logo: { "@type": "ImageObject", url: LOGO_URL },
    },
    mainEntityOfPage: { "@type": "WebPage", "@id": `${BASE_URL}/blog/${post.slug}` },
    url: `${BASE_URL}/blog/${post.slug}`,
    articleSection: post.category,
    keywords: post.keywords?.join(", "),
    wordCount: post.content ? post.content.split(/\s+/).length : undefined,
    inLanguage: "en-US",
  };
}
